# Generated by Django 3.1.2 on 2022-04-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('file', models.ImageField(upload_to='files')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.admin_registration_tb')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.stud_registration_tb')),
            ],
        ),
    ]
